Added accounts module containing signup and login features
uzair-anwar/Facebook-Backend pull request #1
Opened 2022-08-10 06:54 UTC by uzair-anwar

In this module, we apply server-side validation on body content. Apply JWT authentication and hashing passwords.
In this, we also connect the MySQL database by using an ORM named Sequelize.

2022-08-10 20:36 UTC, Sufyan-Abbada requested changes
Overall code quality was way improved than previous one.

2022-08-10 20:36 UTC, Sufyan-Abbada commented on server.js
>  require("dotenv").config();
Kindly move it after all the declarations.

2022-08-10 20:36 UTC, Sufyan-Abbada commented on server.js
>      origin: ["http://localhost:3000"],
Please move these configs to ENV.

2022-08-10 20:36 UTC, Sufyan-Abbada commented on server.js
> +app.use("/auth", authRoutes);
👍

2022-08-10 20:36 UTC, Sufyan-Abbada commented on server.js
>  const port = process.env.PORT;
Can you please use `process.env.PORT` as it is?

2022-08-10 20:36 UTC, Sufyan-Abbada commented on server.js
>    console.log(`Example app listening on port ${port}!`);
Example App, seriously???

2022-08-10 20:36 UTC, Sufyan-Abbada commented on src/Controllers/accounts.js
> +const user = require("../Database/models/user");
Kindly follow proper naming conventions

2022-08-10 20:36 UTC, Sufyan-Abbada commented on src/Controllers/accounts.js
> +  try {
👍

2022-08-10 20:36 UTC, Sufyan-Abbada commented on src/Controllers/accounts.js
> +      res.send({ status: 409, message: "Account already exists" });
Very Good

2022-08-10 20:36 UTC, Sufyan-Abbada commented on src/Controllers/accounts.js
> +      if (newUser) {
Please use Indentation and Line breaks also.

2022-08-10 20:36 UTC, Sufyan-Abbada commented on src/Controllers/accounts.js
> +    const tempUser = await user.findOne({ where: { email: req.body.email } });
`tempUser` doesn't seem nice Variable name.

2022-08-10 20:36 UTC, Sufyan-Abbada commented on src/Database/migrations/20220808192334-user.js
> +module.exports = {
Please use line breaks where necessary

2022-08-10 20:36 UTC, Sufyan-Abbada commented on src/Database/models/user.js
> +const { Sequelize, DataTypes } = require("sequelize");
Please remove this file, if not necessary

2022-08-10 20:36 UTC, Sufyan-Abbada commented on src/middlewares/authValidations.js
> +    .trim(),
Please don't repeat the same code. Please use DRY approach.

2022-08-10 20:36 UTC, Sufyan-Abbada commented on src/routes/authRoutes.js
> +const { login, signup, getAll } = require("../Controllers/accounts");
Please use proper directory naming conventions

2022-08-11 07:58 UTC, uzair-anwar commented on server.js
>      origin: ["http://localhost:3000"],
Moved

2022-08-11 08:00 UTC, uzair-anwar commented on server.js
>  const port = process.env.PORT;
Resolved

2022-08-11 08:09 UTC, uzair-anwar commented on src/Database/models/user.js
> +const { Sequelize, DataTypes } = require("sequelize");
This is necessary Because, with the object of the model, We call the function of sequelize.

2022-08-11 10:36 UTC, uzair-anwar commented on src/middlewares/authValidations.js
> +    .trim(),
Applied

2022-08-15 12:40 UTC, Sufyan-Abbada approved these changes
Good Work

2022-08-15 12:41 UTC, merged