Added posts module containing CRUD
uzair-anwar/Facebook-Backend pull request #2
Opened 2022-08-10 06:59 UTC by uzair-anwar

In this module, we apply server-side validations for post content and also check the JWT token. we store posts in MySQL database through ORM name sequelize. and also perform other operations like edited, getting all posts,s and deleting a post

2022-08-10 20:52 UTC, Sufyan-Abbada requested changes

2022-08-10 20:52 UTC, Sufyan-Abbada commented on server.js
> +sequelize.sync();
Use Migrations rather than Schema syncing.

2022-08-10 20:52 UTC, Sufyan-Abbada commented on src/Controllers/posts.js
> +        status: 400,
I don't think, 400 is not a better status if posts are not present.

2022-08-10 20:52 UTC, Sufyan-Abbada commented on src/Controllers/posts.js
> +exports.editPost = async (req, res, next) => {
Please be consistent in your code regarding quality.

2022-08-10 20:52 UTC, Sufyan-Abbada commented on src/Controllers/posts.js
> +      { title: req.body.title, content: req.body.content },
Create a logic that, if the user only changes one factor, then the code should not overburden the server with useless replacing.

2022-08-10 20:52 UTC, Sufyan-Abbada commented on src/Controllers/posts.js
> +    if (updatedPost[0] === 1) {
Please modify this logic rather than hard code checking of the response

2022-08-10 20:52 UTC, Sufyan-Abbada commented on src/Controllers/posts.js
> +    const rowDeleted = await post.destroy({
Please use self-explanatory variable names.

2022-08-10 20:52 UTC, Sufyan-Abbada commented on src/Database/migrations/20220809102206-post.js
> +      },
Where is the association of the Posts table with Users?

2022-08-10 20:52 UTC, Sufyan-Abbada commented on src/Database/models/post.js
>  const { Sequelize, DataTypes } = require("sequelize");
Please don't use double approaches for a single task within the same project.

2022-08-11 11:11 UTC, uzair-anwar commented on src/Controllers/posts.js
> +        status: 400,
changed to status code 204

2022-08-11 22:55 UTC, uzair-anwar commented on src/Database/models/post.js
>  const { Sequelize, DataTypes } = require("sequelize");
A user model is necessary to call the function sequelize. That is why we made this. We can make tables with models if we want and also make tables with migrations. If we make tables with migrations this does not mean we have no more needs for models. That why I also made Post or User model

2022-08-11 22:59 UTC, uzair-anwar commented on src/Controllers/posts.js
> +      { title: req.body.title, content: req.body.content },
If I make a logic for this, then one extra call for API or one find function of sequelize is called. This means that we run an extra query. This is also an overburden for the server. Updating a field has low cost than a single query that's why I do not create logic for this.

2022-08-11 23:08 UTC, uzair-anwar commented on src/Database/migrations/20220809102206-post.js
> +      },
Resolved.

2022-08-11 23:13 UTC, uzair-anwar commented on src/Controllers/posts.js
> +    if (updatedPost[0] === 1) {
Resolved

2022-08-15 11:41 UTC, uzair-anwar commented on server.js
> +sequelize.sync();
Resolved.

2022-08-15 12:48 UTC, Sufyan-Abbada reviewed
Good work. 
Please don't ever expose sensitive data in your code base. Use `gitignore` and `ENV` for such stuff.

2022-08-15 12:48 UTC, Sufyan-Abbada commented on server.js
>      origin: ["http://localhost:3000"],
Localhost should not be present in files. Please move it to `ENV`.

2022-08-15 12:48 UTC, Sufyan-Abbada commented on server.js
> +    methods: "GET,PUT,PATCH,POST,DELETE",
Please move these methods in `ENV`.

2022-08-15 12:48 UTC, Sufyan-Abbada commented on src/Controllers/posts.js
> +      { title: req.body.title, content: req.body.content },
Good 👍

2022-08-15 14:11 UTC, uzair-anwar commented on server.js
>      origin: ["http://localhost:3000"],
Moved

2022-08-15 18:37 UTC, Sufyan-Abbada approved these changes

2022-08-15 19:20 UTC, merged